### ISSUE TITLE
LoadSettings slow

### ISSUE THREAD

**Issue by serdam55** [Invisionware/Invisionware.Settings#1]
Hi there,
when I execute LoadSettings the application will stuck for 1 second why?

**Comment by ravensorb** [comment]
Were are you loading the settings from?  Can you provide some details and code sample to help figure out what is going on?

**Comment by serdam55** [comment]
Hi thanks for the fast reply, so when I click on the Save button this method is firing:

        public void Save()
        {
            SettingsMgr.SaveSettings(SettingsController.SettingsManager);
         
            //Create backup copy
            var storedSettConf = new SettingsConfiguration<Settings>()
                .WriteTo.JsonNet(Globals.ConfigFilePath).ReadFrom.JsonNet(ConfigFilePath);
            
            StoredSettingsMgr = storedSettConf.CreateSettingsMgr();
          
           SettingsController.StoredSettings = StoredSettingsMgr.LoadSettings();
        }

as you can see I need to create a backup copy of the settings. This allow me to check if there are unsaved changed when the user close the settings panel without save. So suppose that:
1. User will check a checkbox in the settings panel
2. User will click on exit button of settings panel
3. The code compare the actual settings and the old settings (StoredSettingsMgr) to check if there are unsaved changes

the problem is that this line:

           SettingsController.StoredSettings = StoredSettingsMgr.LoadSettings();

will freeze the app for at least 1/2 seconds before close the settings panel.
Maybe I don't need to create this mechanism for check unsaved settings?

Thanks

**Comment by ravensorb** [comment]
Hmm the only thing I can think of is that it is taking a while to serialize the settings object (the default is using json.net).  is your settings object complex?

**Comment by serdam55** [comment]
Yep, in the Settings Class I have also 3 other classes with several properties, like that:
   
     public class Settings
     {
             public General { get; set; }
             public Advanced { get; set; }
             public Features { get; set; }     
     }

**Comment by ravensorb** [comment]
Anything that is self-referencing (like a list that has items that have a reference to the parent)?

**Comment by serdam55** [comment]
well, I have some property that update the user interface color, like this for example:

        private string _theme = "blue";
        public string Theme
        {
            get { return _theme; }
            set
            {
                _theme = value.ToLower();
                OnPropertyChanged();

                var theme = Globals.SfVm.SettingsController.Themes
                    .FirstOrDefault(c => c.Name == _theme);

               SettingsController.PaletteHelper
                    .ReplacePalette(theme.Theme.GetPalette());
            }
        }

the set is called each time that the button save is pressed, could be that?

**Comment by ravensorb** [comment]
I think you might just have found your issue :)  If you are doing UI updates on the same thread that is loading the settings I would expect there to be a delay (and possibly even an exception depending on the state of the UI thread).  Try commenting out all of those types of things and calling the load and see what the performance is like.

**Comment by serdam55** [comment]
You're right :) the problem is that line not your method I'm sorry for this. 
Could you suggest me anything to manage this situation? I can't use Task.Run() 'cause this type of method need to be in UI thread.
The method ReplacePalette allow the user to see in real time the new application color selected.

**Comment by ravensorb** [comment]
Couple of ideas
- Have a bool value that enables/disables the UI code (have it default to false so that during loading it doesn't execute (not ideal in terms of separation of concerns however it will work)
- Move the code to an external method and register a PropertyChanged handler that executes it
